apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gzmongodb
spec:
  replicas: 1
  serviceName: gzmongodb
  selector:
    matchLabels:
      app: gzmongodb
  template:
    metadata:
      labels:
        app: gzmongodb
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          # IfNotPresent 仅本地没有镜像时才远程拉，Always 永远都是从远程拉，Never 永远只用本地镜像，本地没有则报错
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data/db # 容器里面的挂载路径
              name: gz-mongo-data    # 卷名字，必须跟下面定义的名字一致
      volumes:
        - name: gz-mongo-data              # 卷名字
          hostPath:
            path: /data/gz-mongo-data      # 节点上的路径
            type: DirectoryOrCreate     # 指向一个目录，不存在时自动创建
#        - name: gz-mongo-data
#            persistentVolumeClaim:
#              claimName: mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: gzmongodb
spec:
  selector:
    app: gzmongodb
  type: ClusterIP
  # HeadLess
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  
